services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rock-paper-scissor
    volumes:
      - ./log-directory:/var/lib/postgresql
    ports:
      - "5332:5432"
    restart: unless-stopped

