services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rps
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres

    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

volumes:
  db:
